// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/message.proto

package message

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Employee struct {
	Id                   int32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BadgeNumber          int32       `protobuf:"varint,2,opt,name=badgeNumber,proto3" json:"badgeNumber,omitempty"`
	FirstName            string      `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string      `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	VacationAccrualRate  float32     `protobuf:"fixed32,5,opt,name=vacationAccrualRate,proto3" json:"vacationAccrualRate,omitempty"`
	VacationAccrued      float32     `protobuf:"fixed32,6,opt,name=vacationAccrued,proto3" json:"vacationAccrued,omitempty"`
	Vacations            []*Vacation `protobuf:"bytes,7,rep,name=vacations,proto3" json:"vacations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_8447775385e7eb85, []int{0}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Employee) GetBadgeNumber() int32 {
	if m != nil {
		return m.BadgeNumber
	}
	return 0
}

func (m *Employee) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Employee) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Employee) GetVacationAccrualRate() float32 {
	if m != nil {
		return m.VacationAccrualRate
	}
	return 0
}

func (m *Employee) GetVacationAccrued() float32 {
	if m != nil {
		return m.VacationAccrued
	}
	return 0
}

func (m *Employee) GetVacations() []*Vacation {
	if m != nil {
		return m.Vacations
	}
	return nil
}

type Vacation struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartDate            int64    `protobuf:"varint,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	Duration             float32  `protobuf:"fixed32,3,opt,name=duration,proto3" json:"duration,omitempty"`
	IsCancelled          bool     `protobuf:"varint,4,opt,name=isCancelled,proto3" json:"isCancelled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vacation) Reset()         { *m = Vacation{} }
func (m *Vacation) String() string { return proto.CompactTextString(m) }
func (*Vacation) ProtoMessage()    {}
func (*Vacation) Descriptor() ([]byte, []int) {
	return fileDescriptor_8447775385e7eb85, []int{1}
}

func (m *Vacation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vacation.Unmarshal(m, b)
}
func (m *Vacation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vacation.Marshal(b, m, deterministic)
}
func (m *Vacation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vacation.Merge(m, src)
}
func (m *Vacation) XXX_Size() int {
	return xxx_messageInfo_Vacation.Size(m)
}
func (m *Vacation) XXX_DiscardUnknown() {
	xxx_messageInfo_Vacation.DiscardUnknown(m)
}

var xxx_messageInfo_Vacation proto.InternalMessageInfo

func (m *Vacation) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Vacation) GetStartDate() int64 {
	if m != nil {
		return m.StartDate
	}
	return 0
}

func (m *Vacation) GetDuration() float32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Vacation) GetIsCancelled() bool {
	if m != nil {
		return m.IsCancelled
	}
	return false
}

type GetAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRequest) Reset()         { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()    {}
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8447775385e7eb85, []int{2}
}

func (m *GetAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequest.Unmarshal(m, b)
}
func (m *GetAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequest.Marshal(b, m, deterministic)
}
func (m *GetAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequest.Merge(m, src)
}
func (m *GetAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRequest.Size(m)
}
func (m *GetAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequest proto.InternalMessageInfo

type GetByBadgeNumberRequest struct {
	BadgeNumber          int32    `protobuf:"varint,1,opt,name=badgeNumber,proto3" json:"badgeNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByBadgeNumberRequest) Reset()         { *m = GetByBadgeNumberRequest{} }
func (m *GetByBadgeNumberRequest) String() string { return proto.CompactTextString(m) }
func (*GetByBadgeNumberRequest) ProtoMessage()    {}
func (*GetByBadgeNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8447775385e7eb85, []int{3}
}

func (m *GetByBadgeNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByBadgeNumberRequest.Unmarshal(m, b)
}
func (m *GetByBadgeNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByBadgeNumberRequest.Marshal(b, m, deterministic)
}
func (m *GetByBadgeNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByBadgeNumberRequest.Merge(m, src)
}
func (m *GetByBadgeNumberRequest) XXX_Size() int {
	return xxx_messageInfo_GetByBadgeNumberRequest.Size(m)
}
func (m *GetByBadgeNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByBadgeNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByBadgeNumberRequest proto.InternalMessageInfo

func (m *GetByBadgeNumberRequest) GetBadgeNumber() int32 {
	if m != nil {
		return m.BadgeNumber
	}
	return 0
}

type EmployeeRequest struct {
	Employee             *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EmployeeRequest) Reset()         { *m = EmployeeRequest{} }
func (m *EmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*EmployeeRequest) ProtoMessage()    {}
func (*EmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8447775385e7eb85, []int{4}
}

func (m *EmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeRequest.Unmarshal(m, b)
}
func (m *EmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeRequest.Marshal(b, m, deterministic)
}
func (m *EmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeRequest.Merge(m, src)
}
func (m *EmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_EmployeeRequest.Size(m)
}
func (m *EmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeRequest proto.InternalMessageInfo

func (m *EmployeeRequest) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

type EmployeeResponse struct {
	Employee             *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EmployeeResponse) Reset()         { *m = EmployeeResponse{} }
func (m *EmployeeResponse) String() string { return proto.CompactTextString(m) }
func (*EmployeeResponse) ProtoMessage()    {}
func (*EmployeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8447775385e7eb85, []int{5}
}

func (m *EmployeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeResponse.Unmarshal(m, b)
}
func (m *EmployeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeResponse.Marshal(b, m, deterministic)
}
func (m *EmployeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeResponse.Merge(m, src)
}
func (m *EmployeeResponse) XXX_Size() int {
	return xxx_messageInfo_EmployeeResponse.Size(m)
}
func (m *EmployeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeResponse proto.InternalMessageInfo

func (m *EmployeeResponse) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

func init() {
	proto.RegisterType((*Employee)(nil), "Employee")
	proto.RegisterType((*Vacation)(nil), "Vacation")
	proto.RegisterType((*GetAllRequest)(nil), "GetAllRequest")
	proto.RegisterType((*GetByBadgeNumberRequest)(nil), "GetByBadgeNumberRequest")
	proto.RegisterType((*EmployeeRequest)(nil), "EmployeeRequest")
	proto.RegisterType((*EmployeeResponse)(nil), "EmployeeResponse")
}

func init() { proto.RegisterFile("pb/message.proto", fileDescriptor_8447775385e7eb85) }

var fileDescriptor_8447775385e7eb85 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x4f, 0xab, 0x9b, 0x40,
	0x14, 0xc5, 0x19, 0xf3, 0x4f, 0x6f, 0x68, 0x62, 0xa7, 0x8b, 0x4a, 0xc8, 0x42, 0x84, 0x52, 0xa1,
	0xd4, 0x86, 0x74, 0xd3, 0xd2, 0x45, 0x49, 0xda, 0x92, 0x5d, 0x16, 0x13, 0xe8, 0x7e, 0xd4, 0xdb,
	0x20, 0x68, 0xb4, 0xce, 0x28, 0xe4, 0xeb, 0xf6, 0x6b, 0x74, 0xf3, 0x70, 0x9e, 0x7f, 0x12, 0x93,
	0x07, 0x59, 0xce, 0xef, 0xdc, 0x33, 0xe3, 0x39, 0x17, 0xc1, 0xcc, 0xfc, 0x4f, 0x09, 0x0a, 0xc1,
	0x8f, 0xe8, 0x65, 0x79, 0x2a, 0x53, 0xe7, 0x3f, 0x01, 0xfd, 0x57, 0x92, 0xc5, 0xe9, 0x19, 0x91,
	0xce, 0x40, 0x8b, 0x42, 0x8b, 0xd8, 0xc4, 0x1d, 0x31, 0x2d, 0x0a, 0xa9, 0x0d, 0x53, 0x9f, 0x87,
	0x47, 0xdc, 0x17, 0x89, 0x8f, 0xb9, 0xa5, 0x29, 0xe1, 0x12, 0xd1, 0x25, 0x18, 0x7f, 0xa2, 0x5c,
	0xc8, 0x3d, 0x4f, 0xd0, 0x1a, 0xd8, 0xc4, 0x35, 0x58, 0x07, 0xe8, 0x02, 0xf4, 0x98, 0xd7, 0xe2,
	0x50, 0x89, 0xed, 0x99, 0xae, 0xe0, 0x4d, 0xc9, 0x03, 0x2e, 0xa3, 0xf4, 0xb4, 0x09, 0x82, 0xbc,
	0xe0, 0x31, 0xe3, 0x12, 0xad, 0x91, 0x4d, 0x5c, 0x8d, 0xdd, 0x93, 0xa8, 0x0b, 0xf3, 0x2b, 0x8c,
	0xa1, 0x35, 0x56, 0xd3, 0x7d, 0x4c, 0xdf, 0x83, 0xd1, 0x20, 0x61, 0x4d, 0xec, 0x81, 0x3b, 0x5d,
	0x1b, 0xde, 0xef, 0x9a, 0xb0, 0x4e, 0x73, 0x4a, 0xd0, 0x1b, 0x7c, 0x13, 0x7e, 0x09, 0x86, 0x90,
	0x3c, 0x97, 0x3f, 0xab, 0xcf, 0xaa, 0xa2, 0x0f, 0x58, 0x07, 0xaa, 0x68, 0x61, 0x91, 0x2b, 0xa7,
	0xca, 0xad, 0xb1, 0xf6, 0x5c, 0xd5, 0x16, 0x89, 0x1f, 0xfc, 0x14, 0x60, 0x1c, 0x63, 0xa8, 0x92,
	0xeb, 0xec, 0x12, 0x39, 0x73, 0x78, 0xb5, 0x43, 0xb9, 0x89, 0x63, 0x86, 0x7f, 0x0b, 0x14, 0xd2,
	0xf9, 0x06, 0x6f, 0x77, 0x28, 0xb7, 0xe7, 0x6d, 0xd7, 0x6d, 0x2d, 0xf5, 0x97, 0x40, 0x6e, 0x96,
	0xe0, 0x7c, 0x81, 0x79, 0xb3, 0xc2, 0xc6, 0xf4, 0x0e, 0x74, 0xac, 0x91, 0x72, 0x54, 0x05, 0xb4,
	0x33, 0xad, 0xe4, 0x7c, 0x05, 0xb3, 0x73, 0x8a, 0x2c, 0x3d, 0x09, 0x7c, 0xd0, 0xba, 0xfe, 0x47,
	0xba, 0x57, 0x0f, 0x98, 0x97, 0x51, 0x80, 0xf4, 0x3b, 0x98, 0xfd, 0x14, 0xd4, 0xf2, 0x5e, 0x08,
	0xb6, 0x78, 0xed, 0xdd, 0xbc, 0xfd, 0x11, 0xc6, 0xcf, 0xbd, 0xd0, 0x99, 0x77, 0x55, 0xd0, 0x9d,
	0xe1, 0x15, 0xa1, 0x1f, 0x60, 0x78, 0xe0, 0x25, 0x52, 0xd3, 0xeb, 0xe5, 0xbf, 0x77, 0xf7, 0x1a,
	0x26, 0xd5, 0x70, 0x75, 0xf9, 0x23, 0xf3, 0x2e, 0x59, 0x11, 0x7f, 0xac, 0x7e, 0x92, 0xcf, 0x4f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xca, 0x4b, 0xbb, 0xdb, 0x38, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmployeeServiceClient is the client API for EmployeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmployeeServiceClient interface {
	GetByBadgeNumber(ctx context.Context, in *GetByBadgeNumberRequest, opts ...grpc.CallOption) (*EmployeeResponse, error)
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (EmployeeService_GetAllClient, error)
	Save(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error)
	SaveAll(ctx context.Context, opts ...grpc.CallOption) (EmployeeService_SaveAllClient, error)
}

type employeeServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmployeeServiceClient(cc *grpc.ClientConn) EmployeeServiceClient {
	return &employeeServiceClient{cc}
}

func (c *employeeServiceClient) GetByBadgeNumber(ctx context.Context, in *GetByBadgeNumberRequest, opts ...grpc.CallOption) (*EmployeeResponse, error) {
	out := new(EmployeeResponse)
	err := c.cc.Invoke(ctx, "/EmployeeService/GetByBadgeNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (EmployeeService_GetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EmployeeService_serviceDesc.Streams[0], "/EmployeeService/GetAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &employeeServiceGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EmployeeService_GetAllClient interface {
	Recv() (*EmployeeResponse, error)
	grpc.ClientStream
}

type employeeServiceGetAllClient struct {
	grpc.ClientStream
}

func (x *employeeServiceGetAllClient) Recv() (*EmployeeResponse, error) {
	m := new(EmployeeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *employeeServiceClient) Save(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error) {
	out := new(EmployeeResponse)
	err := c.cc.Invoke(ctx, "/EmployeeService/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) SaveAll(ctx context.Context, opts ...grpc.CallOption) (EmployeeService_SaveAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EmployeeService_serviceDesc.Streams[1], "/EmployeeService/SaveAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &employeeServiceSaveAllClient{stream}
	return x, nil
}

type EmployeeService_SaveAllClient interface {
	Send(*EmployeeRequest) error
	Recv() (*EmployeeResponse, error)
	grpc.ClientStream
}

type employeeServiceSaveAllClient struct {
	grpc.ClientStream
}

func (x *employeeServiceSaveAllClient) Send(m *EmployeeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *employeeServiceSaveAllClient) Recv() (*EmployeeResponse, error) {
	m := new(EmployeeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EmployeeServiceServer is the server API for EmployeeService service.
type EmployeeServiceServer interface {
	GetByBadgeNumber(context.Context, *GetByBadgeNumberRequest) (*EmployeeResponse, error)
	GetAll(*GetAllRequest, EmployeeService_GetAllServer) error
	Save(context.Context, *EmployeeRequest) (*EmployeeResponse, error)
	SaveAll(EmployeeService_SaveAllServer) error
}

func RegisterEmployeeServiceServer(s *grpc.Server, srv EmployeeServiceServer) {
	s.RegisterService(&_EmployeeService_serviceDesc, srv)
}

func _EmployeeService_GetByBadgeNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByBadgeNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).GetByBadgeNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmployeeService/GetByBadgeNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).GetByBadgeNumber(ctx, req.(*GetByBadgeNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmployeeServiceServer).GetAll(m, &employeeServiceGetAllServer{stream})
}

type EmployeeService_GetAllServer interface {
	Send(*EmployeeResponse) error
	grpc.ServerStream
}

type employeeServiceGetAllServer struct {
	grpc.ServerStream
}

func (x *employeeServiceGetAllServer) Send(m *EmployeeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _EmployeeService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmployeeService/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).Save(ctx, req.(*EmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_SaveAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmployeeServiceServer).SaveAll(&employeeServiceSaveAllServer{stream})
}

type EmployeeService_SaveAllServer interface {
	Send(*EmployeeResponse) error
	Recv() (*EmployeeRequest, error)
	grpc.ServerStream
}

type employeeServiceSaveAllServer struct {
	grpc.ServerStream
}

func (x *employeeServiceSaveAllServer) Send(m *EmployeeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *employeeServiceSaveAllServer) Recv() (*EmployeeRequest, error) {
	m := new(EmployeeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _EmployeeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "EmployeeService",
	HandlerType: (*EmployeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByBadgeNumber",
			Handler:    _EmployeeService_GetByBadgeNumber_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _EmployeeService_Save_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAll",
			Handler:       _EmployeeService_GetAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SaveAll",
			Handler:       _EmployeeService_SaveAll_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/message.proto",
}
